// <auto-generated />
using DangNgocTuong140.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DangNgocTuong140.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240106071621_Create_table_HocSinh_LopHoc")]
    partial class Create_table_HocSinh_LopHoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DangNgocTuong140.Models.HocSinh", b =>
                {
                    b.Property<string>("MaHocSinh")
                        .HasColumnType("TEXT");

                    b.Property<float>("Diem")
                        .HasColumnType("REAL");

                    b.Property<int>("SoDienThoai")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaHocSinh");

                    b.ToTable("HocSinh");
                });

            modelBuilder.Entity("DangNgocTuong140.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLopHoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaHocSinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLopHoc")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaLopHoc");

                    b.HasIndex("MaHocSinh");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("DangNgocTuong140.Models.LopHoc", b =>
                {
                    b.HasOne("DangNgocTuong140.Models.HocSinh", "HocSinh")
                        .WithMany()
                        .HasForeignKey("MaHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");
                });
#pragma warning restore 612, 618
        }
    }
}
